/********************************************************************
* testCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error testCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabletestCint();
extern void G__cpp_setup_inheritancetestCint();
extern void G__cpp_setup_typetabletestCint();
extern void G__cpp_setup_memvartestCint();
extern void G__cpp_setup_globaltestCint();
extern void G__cpp_setup_memfunctestCint();
extern void G__cpp_setup_functestCint();
extern void G__set_cpp_environmenttestCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGeoBBOx_v.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__testCintLN_TClass;
extern G__linked_taginfo G__testCintLN_TBuffer;
extern G__linked_taginfo G__testCintLN_TMemberInspector;
extern G__linked_taginfo G__testCintLN_TObject;
extern G__linked_taginfo G__testCintLN_TNamed;
extern G__linked_taginfo G__testCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__testCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__testCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testCintLN_TGeoBBox;
extern G__linked_taginfo G__testCintLN_TGeoMatrix;
extern G__linked_taginfo G__testCintLN_TGeoShape;
extern G__linked_taginfo G__testCintLN_TGeoBBox_v;

/* STUB derived class for protected member access */
