//script showing the results of the parallel and sequential modes on 16 detectors
//the script reads the data generated by the shell script stressP in the the directory results.
//to run this script do
//  root > .x stats.C+
//
#include "TCanvas.h"
#include "TH2.h"
#include "TStyle.h"
#include "TLegend.h"

void Process(const char *geom,Int_t &safetys, Int_t &stepss, Int_t &safetyp, Int_t &stepsp, Float_t &cps, Float_t &cpp) {
   if (strstr(geom,"lhcb")) geom = "lhcbfull";
   if (strstr(geom,"minos")) geom = "minos_near";
   FILE *fp;
   Float_t rt;
   Int_t single;
   fp = fopen(Form("results/%s.root_1.dat",geom),"r");
   if (!fp) {
      safetys=1; stepss=1; cps= 0.1;
   } else {
      fscanf(fp,"%d %d %d %g %g",&single,&safetys, &stepss,&rt, &cps);
   }
   fclose(fp);
   fp = fopen(Form("results/%s.root_0.dat",geom),"r");
   if (!fp) {
      safetyp=1; stepsp=1; cpp= 0.1;
   } else {
      fscanf(fp,"%d %d %d %g %g",&single,&safetyp, &stepsp,&rt, &cpp);
   }
   fclose(fp);
   
}

void stats() {
   Int_t colors = kBlue;
   Int_t colorp = kRed;
   Float_t barw = 0.4;
   const Int_t nexp = 16;
   const char *names[nexp] = {"alice","alice2","atlas","cms","lhcb","belle","babar2","btev","bes","aleph","cdf","star","phenix","hades","na49","minos"};
   TH1F *htimes = new TH1F("htimes","time sequential",nexp,0,nexp);
   htimes->SetBarWidth(barw);
   htimes->GetXaxis()->SetLabelSize(0.08);
   htimes->GetYaxis()->SetLabelSize(0.06);
   Int_t i;
   for (i=0;i<nexp;i++) htimes->GetXaxis()->SetBinLabel(i+1,names[i]);
   TH1F *htimep = (TH1F*)htimes->Clone("htimep");
   htimep->SetTitle("cpu time");
   TH1F *hsafetyp = (TH1F*)htimes->Clone("hsafetyp");
   hsafetyp->SetTitle("Number of safetys");
   TH1F *hsafetys = (TH1F*)htimes->Clone("hsafetys");
   hsafetys->SetTitle("number of safetys sequential");
   TH1F *hstepsp = (TH1F*)htimes->Clone("hstepsp");
   hstepsp->SetTitle("number of steps");
   TH1F *hstepss = (TH1F*)htimes->Clone("hstepss");
   hstepss->SetTitle("Number of steps sequential");
   TH1F *htimeps = (TH1F*)htimes->Clone("htimeps");
   htimeps->SetTitle("time_parallel/time_sequential");
   TH1F *hsafetyps = (TH1F*)htimes->Clone("hsafetyps");
   hsafetyps->SetTitle("ratio calls safety_parallel/sequential");
   TH1F *hstepsps = (TH1F*)htimes->Clone("hstepsps");
   hstepsps->SetTitle("ratio call steps_parallel/sequential");
   TH1F *hsafetyss = (TH1F*)htimes->Clone("hsafetyss");
   hsafetyss->SetTitle("ratio calls safety/step sequential");
   TH1F *hsafetysp = (TH1F*)htimes->Clone("hsafetyspp");
   hsafetysp->SetTitle("ratio calls safety/step parallel");
                       
                       
   Float_t cps, cpp;
   Int_t safetys,safetyp,stepss,stepsp;
   for (i=0;i<nexp;i++) {
      Process(names[i],safetys,stepss, safetyp,stepsp,cps,cpp);
      printf("names=%s, safetys=%d, stepss=%d, safetyp=%d, steposp=%d, cps=%g, cpp=%g\n",names[i],safetys,stepss,safetyp,stepsp,cps,cpp);
      htimep->Fill(i,cpp);
      htimes->Fill(i,cps);
      hsafetyp->Fill(i,safetyp);
      hsafetys->Fill(i,safetys);
      hstepsp->Fill(i,stepsp);
      hstepss->Fill(i,stepss);
   }
   gStyle->SetOptStat(0);
   TCanvas *c1 = new TCanvas("c1","c1",0,0,1200,900);
   c1->Divide(2,3);
   //time sequential and parallel
   c1->cd(1);
   gPad->SetLogy();
   gPad->SetGridx();
   gPad->SetGridy();
   htimes->SetFillColor(colors);
   htimes->SetBarOffset(0);
   htimep->SetFillColor(colorp);
   htimep->SetBarOffset(barw);
   htimep->Draw("bar2");
   htimes->Draw("bar2 same");
   TLegend *leg = new TLegend(0.75,0.7,0.88,0.89);
   leg->AddEntry(htimes,"sequential");
   leg->AddEntry(htimep,"parallel");
   leg->Draw();
   //Number of calls to safety
   c1->cd(3);
   gPad->SetLogy();
   gPad->SetGridx();
   gPad->SetGridy();
   hsafetys->SetFillColor(colors);
   hsafetys->SetBarOffset(0);
   hsafetyp->SetFillColor(colorp);
   hsafetyp->SetBarOffset(barw);
   hsafetyp->Draw("bar2");
   hsafetys->Draw("bar2 same");
   //Number of steps
   c1->cd(5);
   gPad->SetLogy();
   gPad->SetGridx();
   gPad->SetGridy();
   hstepss->SetFillColor(colors);
   hstepss->SetBarOffset(0);
   hstepsp->SetFillColor(colorp);
   hstepsp->SetBarOffset(barw);
   hstepsp->Draw("bar2");
   hstepss->Draw("bar2 same");
   //speed-up
   c1->cd(2);
   gPad->SetGridx();
   gPad->SetGridy();
   TH1F *htimeratio = (TH1F*)htimes->Clone("htimeratio");
   htimeratio->SetTitle("100*(1-parallel/sequential)");
   for (i=1;i<=nexp;i++) htimeratio->SetBinContent(i,100-100*htimep->GetBinContent(i)/htimes->GetBinContent(i));
   htimeratio->Draw();
   //time per safety call
   c1->cd(4);
   gPad->SetGridx();
   gPad->SetGridy();
   TH1F *hsafetyst = (TH1F*)hsafetys->Clone("hsafetyst");
   TH1F *hsafetypt = (TH1F*)hsafetyp->Clone("hsafetypt");
   hsafetypt->SetTitle("time per safety call in microseconds");
   for (i=1;i<=nexp;i++) {
      hsafetyst->SetBinContent(i,1e6*htimes->GetBinContent(i)/hsafetys->GetBinContent(i));
      hsafetypt->SetBinContent(i,1e6*htimep->GetBinContent(i)/hsafetyp->GetBinContent(i));
   }
   hsafetypt->Draw("bar2");
   hsafetyst->Draw("bar2 same");
   //time per step call
   c1->cd(6);
   gPad->SetGridx();
   gPad->SetGridy();
   TH1F *hstepst = (TH1F*)hstepss->Clone("hstepst");
   TH1F *hsteppt = (TH1F*)hstepsp->Clone("hsteppt");
   hsteppt->SetTitle("time per step call in microseconds");
   for (i=1;i<=nexp;i++) {
      hstepst->SetBinContent(i,1e6*htimes->GetBinContent(i)/hstepss->GetBinContent(i));
      hsteppt->SetBinContent(i,1e6*htimep->GetBinContent(i)/hstepsp->GetBinContent(i));
   }
   hsteppt->Draw("bar2");
   hstepst->Draw("bar2 same");
   //make pdf of canvas
   c1->cd();
   c1->Print("stats.pdf");
}