//===--- GeantScheduler.h - Geant-V -----------------------------*- C++ -*-===//
//
//                     Geant-V Prototype               
//
//===----------------------------------------------------------------------===//
/**
 * @file GeantScheduler.h
 * @brief Implementation of the GeantV scheduler running in a single thread. Collects tracks
 * from all threads via an input queue and fills baskets corresponding to each
 * volume, which are then injected in the main work queue.
 * @author Andrei Gheata 
 */
//===----------------------------------------------------------------------===//

#ifndef GEANT_SCHEDULER
#define GEANT_SCHEDULER

#ifndef ROOT_TObject
#include "TObject.h"
#endif

#ifdef __STAT_DEBUG
#include "GeantTrackStat.h"
#endif

#if __cplusplus >= 201103L
#include <atomic>
#endif

#include "TMutex.h"

class concurrent_queue;
class GeantTrack;
class GeantBasket;
class GeantBasketMgr;

/**
 * @brief Class GeantScheduler
 * @details Dispatcher running in a single thread. Collects tracks
 * from all threads via an input queue and fills baskets corresponding to each
 * volume, which are then injected in the main work queue.
 * 
 */
class GeantScheduler : public TObject {
protected:
  Int_t fNvolumes;                   /** Number of active volumes in the geometry */
  Int_t fNpriority;                  /** Number of priority baskets held */
  GeantBasketMgr **fBasketMgr;       /** Array of basket managers */
  GeantBasketMgr *fGarbageCollector; /** Garbage collector manager */
#if __cplusplus >= 201103L
  std::atomic_int *fNtracks; /**[fNvolumes] Number of tracks per volume */
  std::atomic_int  fCrtMgr;  /** Current basket manager being garbage collected */
  std::atomic_bool fCollecting;      /** Flag marking colecting tracks for priority events */
#endif
  Int_t fPriorityRange[2]; /** Prioritized events */
#ifdef __STAT_DEBUG
  GeantTrackStat fPStat; /** Statistics for the pending tracks */
  GeantTrackStat fQStat; /** Statistics for the queued tracks */
  GeantTrackStat fTStat; /** Statistics for the transported tracks */
#endif

private:

  /** 
   * @brief GeantScheduler copy constructor 
   * @details Not allowed
   */
  GeantScheduler(const GeantScheduler &);

  /** 
   * @brief Function operator= 
   * @details Not allowed
   */
  GeantScheduler &operator=(const GeantScheduler &);

public:

  /** GeantScheduler default constructor */
  GeantScheduler();

  /** GeantScheduler destructor */
  virtual ~GeantScheduler();

  /**
   * @brief Schedule a new track
   * 
   * @param track Track to be scheduled
   */
  Int_t AddTrack(GeantTrack &track);

  /**
   * @brief Re-schedule all tracks from an output basket
   * @details Transported baskets contain tracks exiting the current volume,
   * tracks killed and new tracks generated by physics along the step. These tracks
   * have to be re-scheduled for transport or bookkeeped for removal. 
   *
   * @param output Transported basket
   * @param ntot Total number of tracks
   * @param nnew Number of new tracks
   * @param nkilled Number of killed tracks
   */
  Int_t AddTracks(GeantBasket *output, Int_t &ntot, Int_t &nnew, Int_t &nkilled, GeantBasketMgr *prioritizer);

  /** @brief Function to adjust the basket size automatically */
  void AdjustBasketSize();

  /** @brief Function to create initially baskets */
  void CreateBaskets();

  /** @brief Function to clean baskets */
  void CleanBaskets();

  /** 
   * @brief Function to collect all tracks from prioritized events 
   * @param collector Garbage collector (one per worker thread)
   */
  Int_t CollectPrioritizedPerThread(GeantBasketMgr *collector);

  /** @brief Function to collection prioritized tracks and inject into transport queue */
  Int_t CollectPrioritizedTracks();

  /**
   * @brief Getter for the array of basket managers
   * return Array of basket managers
   * */
  GeantBasketMgr **GetBasketManagers() const { return fBasketMgr; }

  /**
   * @brief Getter for the garbage collector
   * @return Garbage collector manager
   */
  GeantBasketMgr *GetGarbageCollector() const { return fGarbageCollector; }

#if __cplusplus >= 201103L

  /**
   * @brief Function to return N tracks per volume
   * 
   * @param ib Basket manager id
   * @return return number of tracks per volume
   */
  Int_t GetNtracks(Int_t ib) { return fNtracks[ib].load(); }

  /**
   * @brief Getter for collecting flag
   * @return Value of fCollecting flag
   */
   Bool_t IsCollecting() const { return fCollecting.load(); }
   
  /**
   * @brief Setter for collecting flag
   */
   void SetCollecting(Bool_t flag) { fCollecting.store(flag); }
   
#endif

  /**
   * @brief Function to return N priority baskets per volume
   * @return Number of priority baskets held
   */
  Int_t GetNpriority() const { return fNpriority; }

  /**
   * @brief Function to return N volumes
   * @return Number of active volumes in the geometry
   */
  Int_t GetNvolumes() const { return fNvolumes; }

  /**
   * @brief Function to return the range of prioritized events
   * 
   * @param min Minimum value of range
   * @param max Maximum value of range
   */
  void SetPriorityRange(Int_t min, Int_t max) {
    fPriorityRange[0] = min;
    fPriorityRange[1] = max;
  }
#ifdef __STAT_DEBUG

  /**
   * @brief [Function to return statistic of pending tracks
   * @return Statistics for the pending tracks
   */
  GeantTrackStat &GetPendingStat() { return fPStat; }

  /**
   * @brief Function to return statistic of queued tracks
   * @return Statistics for the queued tracks
   */
  GeantTrackStat &GetQueuedStat() { return fQStat; }

  /**
   * @brief Function to return statistic of transported tracks
   * @return Statistics for the transported tracks
   */
  GeantTrackStat &GetTransportStat() { return fTStat; }
#endif

  /** @brief Function to flush list of priority tracks */
  Int_t FlushPriorityBaskets();

  /** @brief Garbage collection function */
  Int_t GarbageCollect();

  /** @brief Function to print size */
  void PrintSize() const;

  /** @brief Function to returns size */
  size_t Sizeof() const;

  ClassDef(GeantScheduler, 1) // Main basket scheduler
};
#endif
