#!/usr/bin/env bash

THIS=$(dirname $0)
source $THIS/jk-setup-test.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS $WORKSPACE $BACKEND

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

#---Run the CTest script depending on the compiler------------------------------------------
ctest -VV -S ${THIS}/../geantv-ctest.cmake,Nightly || true




