#!/usr/bin/env bash

THIS=$(dirname $0)
echo source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS $BACKEND > setup.sh
source $THIS/jk-setup.sh $LABEL $COMPILER $BUILDTYPE $EXTERNALS $BACKEND

echo "Dumping the full environment ---------------------------------------------------------"
env | sort | sed 's/:/:?     /g' | tr '?' '\n'
echo "--------------------------------------------------------------------------------------"

cd $CMAKE_INSTALL_PREFIX/bin/benchmarks/FullCMS
bash ./bench_all.sh

#---Run the CTest script depending on the compiler------------------------------------------
ctest -VV -S ${THIS}/geantv-ctest.cmake
status=$?

exit $status
